spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_learn?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
#    hikari:
#      minimum-idle: 2
#      maximum-pool-size: 5
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 5
      max-wait: 60000

