spring:
  kafka:
    bootstrap-servers: 116.62.107.71:9092
    consumer:
      group-id: mygroup
    producer:
      bootstrap-servers: 116.62.107.71:9092  # broker 地址列表
      acks: 1
#      buffer-memory:
#      compression-type:
#      retries:
#      batch-size: 1024
#      client-id:
    listener:
      concurrency: 5




      